# -*- coding: utf-8 -*-
"""24521509.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZCMpe5BoYsLnSvczqUhINBRjbFTx4l2
"""
#asignment1

!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip chest-xray-pneumonia.zip

import os

print(os.listdir("chest_xray"))
print(os.listdir("chest_xray/train"))

import cv2 as cv
import numpy as np
import os
from tqdm import tqdm

BASE_DIR = "chest_xray"

def collect_data(split="train"):
    images = []
    labels = []

    for img_file in tqdm(os.listdir(os.path.join(BASE_DIR, split, "NORMAL"))):
        img = cv.imread(os.path.join(BASE_DIR, split, "NORMAL", img_file))

        if img is None:
            continue
        img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        img = cv.resize(img, (128, 128)).reshape(-1)
        images.append(img)
        labels.append(1)

    for img_file in tqdm(os.listdir(os.path.join(BASE_DIR, split, "PNEUMONIA"))):
        img = cv.imread(os.path.join(BASE_DIR, split, "PNEUMONIA", img_file))
        if img is None:
            continue
        img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        img = cv.resize(img, (128, 128), interpolation = cv.INTER_LINEAR_EXACT).reshape(-1)
        images.append(img)
        labels.append(-1)
    X = np.stack(images,axis=0)
    Y = np.array(labels)
    return X, Y
X_train, Y_train = collect_data("train")
X_test, Y_test = collect_data("test")

X_train = X_train.astype(np.float32) / 255.0
X_test = X_test.astype(np.float32) / 255.0

from sklearn.decomposition import PCA

pca = PCA(n_components=300)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(X_train_pca.shape, Y_train.shape)

idx_pos = np.where(Y_train == 1)[0]
idx_neg = np.where(Y_train == -1)[0]

n = min(len(idx_pos), len(idx_neg))

np.random.seed(42)
idx_pos = np.random.choice(idx_pos, n, replace=False)
idx_neg = np.random.choice(idx_neg, n, replace=False)

idx_balanced = np.concatenate([idx_pos, idx_neg])
np.random.shuffle(idx_balanced)

X_bal = X_train_pca[idx_balanced]
Y_bal = Y_train[idx_balanced]

print(np.unique(Y_bal, return_counts=True))

import numpy as np

class LinearSVM:
    def __init__(self, lr=0.001, C=1, epochs=100, batch_size=32):
        self.lr = lr
        self.C = C
        self.epochs = epochs
        self.batch_size = batch_size
        self.w = None
        self.b = 0

    def loss(self, X, y):
        margins = 1 - y * (X @ self.w + self.b)
        hinge = np.maximum(0, margins)
        return 0.5 * np.dot(self.w, self.w) + self.C * np.mean(hinge)

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0

        for epoch in range(self.epochs):
            idx = np.random.permutation(n_samples)
            X = X[idx]
            y = y[idx]

            for i in range(0, n_samples, self.batch_size):
                X_batch = X[i:i+self.batch_size]
                y_batch = y[i:i+self.batch_size]

                margins = y_batch * (X_batch @ self.w + self.b)
                mask = margins < 1

                if np.any(mask):
                    dw = self.w - self.C * np.mean(
                        y_batch[mask][:, None] * X_batch[mask],
                        axis=0
                    )
                    db = -self.C * np.mean(y_batch[mask])
                else:
                    dw = self.w
                    db = 0

                self.w -= self.lr * dw
                self.b -= self.lr * db

            if epoch % 10 == 0:
                loss = self.loss(X, y)
                pred = self.predict(X)
                acc = np.mean(pred == y)
                print(f"Epoch {epoch}: {loss:.4f}, acc={acc:.4f}")

    def predict(self, X):
        return np.where(X @ self.w + self.b >= 0.2, 1, -1)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

svm = LinearSVM(
    lr=0.0001,
    C=1,
    epochs=80,
    batch_size=128
)
svm.fit(X_bal, Y_bal)

pred = svm.predict(X_test_pca)

print("Prediction:", np.unique(pred, return_counts=True))
print("Accuracy :", accuracy_score(Y_test, pred))
print("Precision:", precision_score(Y_test, pred, pos_label=-1))
print("Recall   :", recall_score(Y_test, pred, pos_label=-1))
print("F1-score :", f1_score(Y_test, pred, pos_label=-1))

#asignment2
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

svm_lib = LinearSVC(
    C=1,
    loss='hinge',
    max_iter=20000,
    random_state=42
)

svm_lib.fit(X_bal, Y_bal)

scores = svm_lib.decision_function(X_test_pca)

pred_lib = np.sign(scores)
pred_lib[pred_lib == 0] = 1

print("Prediction:", np.unique(pred_lib, return_counts=True))
print("Accuracy :", accuracy_score(Y_test, pred_lib))
print("Precision:", precision_score(Y_test, pred_lib, pos_label=-1))
print("Recall   :", recall_score(Y_test, pred_lib, pos_label=-1))
print("F1-score :", f1_score(Y_test, pred_lib, pos_label=-1))
